export { Navbar } from './navbar'
export { HeroSection } from './hero-section'
export { ServicesSection } from './services-section'
export { PortfolioSection } from './portfolio-section'
export { GalaxyPortfolio } from './galaxy-portfolio'
export { TestimonialsSection } from './testimonials-section'
export { CTASection } from './cta-section'
export { Footer } from './footer'
